---
title: "R Notebook"
output: html_document
---

```{r package_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```


## Loading dataframe in called "my genes"

```{r}
library('plotly')
mygenes <- read.csv('gene_dist_head.tsv', sep = "\t")
read.table(file = 'gene_dist_head.tsv', header = TRUE, sep = "", quot = "\"",)
is.data.frame(mygenes)
```
## Summary of data in my genes

```{r}
library(dplyr)
summary(mygenes)
```
## test graph.r script

```{r}
library(ggplot2) # We load in libraries
library(plotly)
```


```{r}
# We define a factor set of autosomes
autosomes<-c("1","2","3","4","5","6","7","8","9","10",
 "11","12","13","14","15","16","17","18","19","20","21","22")  
# We create a new dataframe called 'genes' which only has autosomes, however we still have those additional factors
autosome_genes<- mygenes[ which(mygenes$chr %in% autosomes), ] 
# We remove the factors and then order them so they are numerical order and not alphabetical
autosome_genes$chr <- factor(autosome_genes$chr, levels = autosomes) 
 # We plot in ggplot 
ggplot(data = autosome_genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
```
## lets put X as the chromosomes and then look at features
```{r}
ggplot(data = autosome_genes) +
 geom_bar(mapping = aes(x = chr, fill = feature))
```


## lets go to polar coordinates:

```{r}
library(ggplot2)
library(plotly)
ggplot(data = autosome_genes) +
 geom_bar(mapping = aes(x = chr, fill = feature), width = 1) +
 coord_polar()
```
## Creating an interactive graph that allows closer look at dataset autsome_genes

```{r}
library(ggplot2)
library(plotly)
p<-ggplot(data = autosome_genes) +  geom_bar(mapping = aes(x = chr, fill = feature), width = 1)
ggplotly(p)
```




